language: ruby
cache: bundler
branches:
  only:
  - master
before_install:
   - rvm install 2.6.5
install:
- gem update --system
- gem install jekyll -v 3.8.5
- gem install bundler -v 2.1.4
- bundle install

script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination site

deploy:
  provider: pages
  local-dir: ./site
  target-branch: master
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: true
  github-token: $fc52de659dd22be7f6eb79debbf5453db4de1b39
  keep-history: true
  on:
    branch: release
