language: ruby
cache: bundler
branches:
  only:
  - master
script:
  - JEKYLL_ENV=production bundle exec jekyll build --destination site
deploy:
  provider: pages
  local-dir: ./site
  target-branch: master
  email: deploy@travis-ci.org
  name: Deployment Bot
  skip-cleanup: true
  github-token: 104c28b3cd034d367c58a3d357d59e8193f80e1f
  keep-history: true
  on:
    branch: master