# site settings
title: Infozy
subtitle: Little Bit of Everything
email: tksudharshan@infozy.tk
description: Infozy offers Students a unique environment for gathering and sharing information that will help them do their jobs with efficiency. At the core, our goal is to capture the intimate conversation between peers and colleagues when they need quick advice from a trusted, experienced source.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://infozy.tk" # the base hostname & protocol for your site
author:
street_address: 15/27, Triplicane 
city: Chennai
state: TN
zip_code: 600005
country: India

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: https://www.linkedin.com/in/andrew-banchich-a4ba1195
pinterest_url:
slack_url:
twitter_url: https://twitter.com/andrewbanchich

# build settings
markdown: kramdown
permalink: /:title/

sass:
  style: compressed

plugins_dir: ./_plugins
jekyll_get:
  - data: github
    json: 'https://api.github.com/users/tks18/repos'
    cache: false
