# Ruby CircleCI 2.1 configuration file
#
# Check https://circleci.com/docs/2.0/ruby/ for more details
#
version: 2.1 


machine:
  environment:
    USER_NAME: tks18
    USER_EMAIL: tksudharshan@gmail.com
  ruby:
    version: 2.6.5

dependencies:
  pre:
    - ./bin/setup

test:
  post:
    - bundle exec jekyll build
    - bundle exec htmlproof ./_site --only-4xx --href-ignore "#"

deployment:
  production:
    branch: master
    commands:
      - ./bin/automated
# What to do next? Set up a test job. Please see 
# https://circleci.com/docs/2.0/configuration-reference/, for more  info on how to get started.
